apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foreman
spec:
  rules:
    - host: foreman-prod.local
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: rails
              port:
                number: 3000

