apiVersion: v2
name: evershop
description: Typescript E-commerce Platform
type: application
version: 0.1.0
appVersion: "2.1.2"
keywords:
  - react
  - ecommerce
  - typescript
  - ecommerce-platform
  - ecommerce-framework 
home: https://evershop.io/
icon: https://evershop.io/img/logo.svg
sources:
  - https://github.com/evershopcommerce/evershop
  - https://hub.docker.com/r/evershop/evershop
  - https://github.com/djjudas21/charts/tree/master/charts/evershop
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Initial release
