{{- if not .Values.configMap.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-ntfy.fullname" . }}-config
  labels:
    {{- include "alertmanager-ntfy.labels" . | nindent 4 }}
data:
  config.yml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}
