{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smtp-relay.fullname" . }}
  labels:
    {{- include "smtp-relay.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  password: {{ .Values.smtp.password | b64enc }}
{{- end }}
