apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-relay.name" . }}
  labels:
    {{- include "smtp-relay.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2525
      protocol: TCP
      name: smtp
    - port: {{ .Values.metrics.port }}
      targetPort: 9154
      protocol: TCP
      name: metrics
  selector:
    {{- include "smtp-relay.selectorLabels" . | nindent 4 }}
