{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webtrees.fullname" . }}
  labels:
    {{- include "webtrees.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  WT_USER: {{ .Values.secret.WT_USER | b64enc }}
  WT_NAME: {{ .Values.secret.WT_NAME | b64enc }}
  WT_PASS: {{ .Values.secret.WT_PASS | b64enc }}
  WT_EMAIL: {{ .Values.secret.WT_EMAIL | b64enc }}
{{- end }}
