---
apiVersion: v2
name: alertify
description: Bridge between Prometheus Alertmanager and Gotify
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - prometheus
  - alertmanager
  - alertify
  - gotify
home: https://github.com/djjudas21/charts/tree/master/charts/alertify
icon: https://raw.githubusercontent.com/gotify/logo/refs/heads/master/gotify-logo.png
sources:
  - https://github.com/djjudas21/alertify
  - https://hub.docker.com/r/djjudas21/alertify
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Add alerting rules
