{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "adventurelog.fullname" . }}
  labels:
    {{- include "adventurelog.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.hosts.frontend }}
      - {{ .Values.ingress.hosts.backend }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.frontend }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "adventurelog.fullname" . }}-frontend
            port:
              number: {{ .Values.frontend.service.port }}
        path: /
        pathType: Prefix
  - host: {{ .Values.ingress.hosts.backend }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "adventurelog.fullname" . }}-backend
            port:
              number: {{ .Values.backend.service.port }}
        path: /
        pathType: Prefix
{{- end }}