apiVersion: v1
kind: Service
metadata:
  name: {{ include "adventurelog.fullname" . }}-frontend
  labels:
    {{- include "adventurelog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adventurelog.selectorLabels" . | nindent 4 }}
    component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adventurelog.fullname" . }}-backend
  labels:
    {{- include "adventurelog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adventurelog.selectorLabels" . | nindent 4 }}
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adventurelog.fullname" . }}-db
  labels:
    {{- include "adventurelog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgis.service.type }}
  ports:
    - port: {{ .Values.postgis.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "adventurelog.selectorLabels" . | nindent 4 }}
    component: postgis