---
apiVersion: v2
appVersion: 1.23.12
description: A fancy self-hosted monitoring tool for your websites and applications
name: uptime-kuma
version: 1.5.18
kubeVersion: ">=1.16.0-0"
keywords:
  - uptime-kuma
  - status
  - status-page
  - monitoring
home: https://github.com/djjudas21/charts/tree/master/charts/incubator/uptime-kuma
icon: https://github.com/louislam/uptime-kuma/raw/master/public/icon.svg
sources:
  - https://github.com/louislam/uptime-kuma
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
dependencies:
  - name: common
    repository: http://bjw-s-labs.github.io/helm-charts/
    version: 1.0.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Migrate to bjw-s-labs
