apiVersion: v2
name: lldap
description: Light LDAP implementation

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.6.1"

keywords:
  - rust
  - security
  - ldap
  - authentication
  - wasm
  - web-assembly
  - opaque

dependencies:
  - name: postgresql
    version: ~15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: ~18
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled

home: https://github.com/djjudas21/charts/tree/master/charts/lldap
sources:
  - https://github.com/lldap/lldap
  - https://hub.docker.com/r/lldap/lldap
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Fix bootstrap image tag
