---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: foreman
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: foreman
      tier: cache
  template:
    metadata:
      name: redis
      labels:
        app: foreman
        tier: cache
    spec:
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pvc
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/data"
          name: redis-pv
