apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecowitt-exporter.fullname" . }}
  labels:
    {{- include "ecowitt-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecowitt-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ecowitt-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ecowitt-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- if .Values.env.debug }}
          - name: DEBUG
            value: "yes"
          - name: FLASK_DEBUG
            value: "1"
          {{- end }}
          - name: TEMPERATURE_UNIT
            value: {{ .Values.env.temperatureUnit }}
          - name: PRESSURE_UNIT
            value: {{ .Values.env.pressureUnit }}
          - name: WIND_UNIT
            value: {{ .Values.env.windUnit }}
          - name: RAIN_UNIT
            value: {{ .Values.env.rainUnit }}
          - name: IRRADIANCE_UNIT
            value: {{ .Values.env.irradianceUnit }}
          - name: DISTANCE_UNIT
            value: {{ .Values.env.distanceUnit }}
          - name: AQI_STANDARD
            value: {{ .Values.env.aqiStandard }}
          - name: PREFIX
            value: {{ .Values.env.prefix }}
          - name: OUTDOOR_LOCATION
            value: {{ .Values.env.outdoorLocation }}
          - name: INDOOR_LOCATION
            value: {{ .Values.env.indoorLocation }}
          - name: TEMP1_LOCATION
            value: {{ .Values.env.temp1Location }}
          - name: TEMP2_LOCATION
            value: {{ .Values.env.temp2Location }}
          - name: TEMP3_LOCATION
            value: {{ .Values.env.temp3Location }}
          - name: TEMP4_LOCATION
            value: {{ .Values.env.temp4Location }}
          - name: TEMP5_LOCATION
            value: {{ .Values.env.temp5Location }}
          - name: TEMP6_LOCATION
            value: {{ .Values.env.temp6Location }}
          - name: TEMP7_LOCATION
            value: {{ .Values.env.temp7Location }}
          - name: TEMP8_LOCATION
            value: {{ .Values.env.temp8Location }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
