{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: service-prometheus
    role: alert-rules
  name: {{ include "ecowitt-exporter.fullname" . }}
spec:
{{ .Files.Get "files/prometheus.rules" }}
{{- end }}
