{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: service-prometheus
    role: alert-rules
  name: {{ include "ecowitt-exporter.fullname" . }}
spec:
  groups:
{{- if .Values.prometheusRules.batteryAlerts }}
{{ .Files.Get "files/ecowitt-battery.rules" }}
{{- end }}
{{- if .Values.prometheusRules.weatherAlerts }}
{{ .Files.Get "files/ecowitt-weather.rules" }}
{{- end }}
{{- end }}
