{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evershop.fullname" . }}
  labels:
    {{- include "evershop.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  DB_HOST: {{ .Values.postgres.DB_HOST | b64enc }}
  DB_PORT: {{ .Values.postgres.DB_PORT | b64enc }}
  DB_PASSWORD: {{ .Values.postgres.DB_PASSWORD | b64enc }}
  DB_USER: {{ .Values.postgres.DB_USER | b64enc }}
  DB_NAME: {{ .Values.postgres.DB_NAME | b64enc }}
{{- end }}
