#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/4d09009bf809b2ce3c06225f61cf229e40d2c08a/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/nathanvaughn/webtrees
  # -- image tag
  # @default -- chart.appVersion
  tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [webtrees-docker documentation](https://github.com/NathanVaughn/webtrees-docker#environment-variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Enable pretty URLs
  PRETTY_URLS: "TRUE"
  # -- webtrees localization setting
  LANG: "en-US"
  # -- Base URL of the installation, with protocol. Must be in the form `http://webtrees.example.com`
  BASE_URL: https://webtrees.example.com
  # -- Database server type
  DB_TYPE: "mysql"
  # -- Database hostname
  DB_HOST: webtrees-mariadb
  # -- Database server port
  DB_PORT: "3306"
  # -- Database username
  DB_USER: webtrees
  # -- Database password
  DB_PASS: webtreespass
  # -- Database to connect to
  DB_NAME: webtrees
  # -- Prefix to give all tables in the database. Set this to a value of "" to have no table prefix.
  DB_PREFIX: "wt_"
  # -- Admin account username
  WT_USER: admin
  # -- Admin account full name
  WT_NAME: Administrator
  # -- Admin account password
  WT_PASS: adminpass
  # -- Admin account email
  WT_EMAIL: admin@example.com

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /var/www/webtrees/data/
    # storageClass: ""

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- <https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml>
mariadb:
  enabled: false
  image:
    repository: bitnamilegacy/mariadb
  architecture: standalone
  auth:
    database: webtrees
    username: webtrees
    password: webtreespass
    rootPassword: webtreesrootpass
  primary:
    persistence:
      enabled: false
      # storageClass: ""
