name: Renovate

on:
  pull_request:
    branches:
      - '**'

env:
  COMMIT_MESSAGE: "chore: Update chart metadata"

jobs:
  update-chart-metadata:
    name: Update Chart Metadata
    runs-on: ubuntu-latest
    env:
      AUTHOR_USER: "$GITHUB_ACTOR"
      AUTHOR_EMAIL: "$GITHUB_ACTOR@users.noreply.github.com"
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell
          filters: |
            charts:
              - charts/**

      - name: Fetch PR
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });
            const pr = response.data.shift();
            core.setOutput("title", pr.title);
            core.setOutput("base_ref", pr.base.ref);
            core.setOutput("labels", pr.labels.map((e) => e.name).filter((e) => e));

      - name: Install helm-docs
        uses: gabe565/setup-helm-docs-action@v1
      - name: Generate Helm docs
        run: |
          set -eu
          ./hack/gen-helm-docs.sh

      - name: Check if commit exists
        id: commit_exists
        env:
          BASE_REF: ${{ steps.pr.outputs.base_ref }}
        run: |
          set -eu
          IFS=$'\n\t'
          commits="$(git rev-list --pretty=oneline "origin/$BASE_REF..HEAD" | cut -d' ' -f2-)"
          if grep -F -e "$COMMIT_MESSAGE" <<<"$commits"; then
            echo 'result=true' >>$GITHUB_OUTPUT
          else
            echo 'result=false' >>$GITHUB_OUTPUT
          fi

      - name: Commit chart version
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.commit_exists.outputs.result == 'false' && !contains(steps.pr.outputs.labels, 'skip-chart-meta')
        with:
          commit_user_name: ${{ env.AUTHOR_USER }}
          commit_user_email: ${{ env.AUTHOR_EMAIL }}
          commit_author: ${{ env.AUTHOR_USER }} <${{ env.AUTHOR_EMAIL }}>
          commit_message: ${{ env.COMMIT_MESSAGE }}
